---
name: Checks and tests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup poetry
        run: >
          curl -sSL https://install.python-poetry.org | python - &&
          echo "$POETRY_HOME/bin" >> "$GITHUB_PATH"
        env:
          POETRY_HOME: "/opt/poetry"
          POETRY_VERSION: 1.8.2

      - name: Install dependencies
        run: poetry install --no-interaction --with=dev

      - name: Lint with isort
        run: poetry run isort --check src

      - name: Lint with black
        run: poetry run black --check src

      - name: Lint with ruff
        run: poetry run ruff check src

      - name: Lint pyright
        run: poetry run pyright src

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup poetry
        run: >
          curl -sSL https://install.python-poetry.org | python - &&
          echo "$POETRY_HOME/bin" >> "$GITHUB_PATH"
        env:
          POETRY_HOME: "/opt/poetry"
          POETRY_VERSION: 1.8.2

      - name: Install dependencies
        run: poetry install --no-interaction --with=dev

      - name: Run tests via pytest
        run: poetry run pytest

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
